Vagrant.configure('2') do |config|
  config.vm.box = 'centos/7'
  config.vm.network "private_network", ip: '192.168.33.10'
  config.vm.hostname = 'centosserver'
  config.vm.provider "virtualbox" do |vb|
    vb.name = 'centos'
    vb.cpus = '1'
    vb.memory = '1024'
  end
    config.vm.provision "shell", inline: <<-SHELL
         sudo yum update -y
	 sudo yum install httpd -y
	 sudo systemctl start httpd.service 
	 sudo systemctl enable httpd.service
	 sudo yum install mariadb-server mariadb -y
	 sudo systemctl start mariadb
	 sudo /Centos/mysql_secure_installation.sh
	 sudo systemctl enable mariadb.service
	 sudo yum install php php-mysql -y
	 sudo systemctl restart httpd.service
     SHELL
end