Vagrant.configure('2') do |config|
  config.vm.box = 'centos/7'
  config.vm.network "private_network", ip: '192.168.33.10'
  config.vm.hostname = 'centosserver'
  config.vm.provider "virtualbox" do |vb|
    vb.name = 'centos'
    vb.cpus = '1'
    vb.memory = '1024'
  end
    config.vm.provision "shell", inline: <<-SHELL
         sudo yum update
	 curl –sL https://rpm.nodesource.com/setup_10.x | sudo bash -
	 sudo yum install –y nodejs -y
	 node -v
	 npm -v
     SHELL
end